Base.string(s1, g::Guild, ss...) = string(s1, g.id, ss...)
Base.string(s1, c::DiscordChannel, ss...) = string(s1, c.id, ss...)
Base.string(s1, u::User, ss...) = string(s1, u.id, ss...)
Base.string(s1, g::Guild, s2, c::DiscordChannel, ss...) = string(s1, g.id, s2, c.id, ss...)
Base.string(s1, g::Guild, s2, u::User, ss...) = string(s1, g.id, s2, u.id, ss...)
Base.string(s1, c::DiscordChannel, s2, m::Message, ss...) = string(s1, c.id, s2, m.id, ss...)
Base.string(s1, c::DiscordChannel, s2, m::Message, ss...) = string(s1, c.id, s2, m.id, ss...)
Base.string(s1, c::DiscordChannel, s2, m::Message, s3, s4, s5, u::User, ss...) = string(s1, c.id, s2, m.id, s3, s4, s5, u.id, ss...)
Base.string(s1, c::DiscordChannel, s2, o::Overwrite, ss...) = string(s1, c.id, s2, o.id, ss...)
Base.string(s1, c::DiscordChannel, s2, u::User, ss...) = string(s1, c.id, s2, u.id, ss...)
Base.string(s1, g::Guild, s2, e::Emoji, ss...) = string(s1, g.id, s2, e.id, ss...)
Base.string(s1, g::Guild, s2, r::Role, ss...) = string(s1, g.id, s2, r.id, ss...)
Base.string(s1, g::Guild, s2, u::User, s3, r::Role, ss...) = string(s1, g.id, s2, u.id, s3, r.id, ss...)
Base.string(s1, g::Guild, s2, i::Integration, ss...) = string(s1, g.id, s2, i.id, ss...)
Base.string(s1, i::Invite, ss...) = string(s1, i.code, ss...)
Base.string(s1, w::Webhook, ss...) = string(s1, w.id, ss...)
# TODO: This is correct?
HTTP.escapeuri(e::Emoji) = escapeuri(e.name)
