@discord_object struct Guild
    id::Snowflake
    name::String
    icon::String
    splash::String
    discovery_splash::String
    owner::Bool
    owner_id::Snowflake
    permissions::Int64
    region::String
    afk_channel_id::Snowflake
    afk_timeout::Int
    embed_enabled::Bool
    embed_channel_id::Snowflake
    verification_level::VerificationLevel
    default_message_notifications::MessageNotificationsLevel
    explicit_content_filter::ExplicitContentFilter
    roles::Vector{Role}
    emojis::Vector{Emoji}
    features::Vector{String}
    mfa_level::MFALevel
    application_id::Snowflake
    widget_enabled::Bool
    widget_channel_id::Snowflake
    system_channel_id::Snowflake
    system_channel_flags::Int
    rules_channel_id::Snowflake
    joined_at::Union{String, DateTime}
    large::Bool
    unavailable::Bool
    member_count::Int
    voice_states::Vector{VoiceState}
    members::Vector{GuildMember}
    channels::Vector{DiscordChannel}
    presences::Vector{PresenceUpdate}
    max_presences::Int
    max_members::Int
    vanity_url_code::String
    description::String
    banner::String
    premium_tier::PremiumTier
    premium_subscription_count::Int
    preferred_locale::String
    public_updates_channel_id::Snowflake
    max_video_channel_users::Int
    approximate_member_count::Int
    approximate_presence_count::Int
end
